const CONSTANTS = {
  // SIZE: 47,
  SIZE: 175,
  CARDS_COUNT: 126,
  SCROLL_SIZE: 6,
  EMPTY_CELL: 'EMPTY_CELL',
  BTNS_DEFAULT_SCALE: 1,
  BTNS_ACTIVE_SCALE: 1.05,
  // BTNS_HOVER_COLOR: 0xd6d3cb,
  BTNS_HOVER_COLOR: 0x9c988f,
  // lang_en: 'Language',
  // lang_ru: 'Язык',
  // lang_de: 'Die Sprache',
  // newGame_en: 'New Game',
  // newGame_ru: 'Новая Игра',
  // newGame_de: 'Neues Spiel',
  // saveGame_en: 'Save Game',
  // saveGame_ru: 'Сохранить Игру',
  // saveGame_de: 'Spiel Speichern',
  // loadGame_en: 'Load Game',
  // loadGame_ru: 'Продолжить Игру',
  // loadGame_de: 'Weiter',
  // sound_en: 'Sound',
  // sound_ru: 'Звук',
  // sound_de: 'Klang',
  // about_en: 'About',
  // about_ru: 'О нас',
  // about_de: 'Über uns',
  // options_en: 'Options',
  // options_ru: 'Настройки',
  // options_de: 'Optionen'
};


export default CONSTANTS;
